name: crash_report_base
resolution: workspace
description: "Provider-agnostic crash reporting and error tracking base layer. Defines the domain contract for capturing exceptions and logs."
version: 0.0.1

environment:
  sdk: ^3.12.2
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  codebase: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
